### ISSUE TITLE
Generated CMakeLists.txt has CATKIN_DEPENDS as DEPENDS

### ISSUE THREAD

**Issue by gavanderhoorn** [moveit/moveit_ikfast#21]
From a generated `CMakeLists.txt`:

```
catkin_package(
  LIBRARIES
  DEPENDS
  moveit_core
  pluginlib
  roscpp
  tf_conversions
)
```

Shouldn't all the packages listed under `DEPENDS` really be `CATKIN_DEPENDS`?

**Comment by isucan** [comment]
They should be. Thanks for finding this!
