### ISSUE TITLE
Missing builddep on cmake_modules in generated ikfast packages

### ISSUE THREAD

**Issue by gavanderhoorn** [moveit/moveit_ikfast#27]
Running `catkin_lint` on a recently (re)generated ikfast plugin package:

```
X_moveit_plugins: CMakeLists.txt(4): warning: find_package(Eigen) before find_package(cmake_modules)
```

This makes sense: `FindEigen.cmake` is part of the `cmake_modules` package, which should be `find_package()`-ed first. It should then also become a `build_depend` of the plugin package.

**Comment by davetcoleman** [comment]
Can you make the fix in this file?
https://github.com/ros-planning/moveit_ikfast/blob/master/templates/CMakeLists.txt
Thanks!
