### ISSUE TITLE
templates: plugin desc CMake install target missing 'planning group name'

### ISSUE THREAD

**Issue by gavanderhoorn** [moveit/moveit_ikfast#28]
As per subject.

The generated `CMakeLists.txt` does not take the _planning group name_ into account when setting up the install rule for the `*_plugin_description.xml` file. The group name _is used_ when creating the plugin description file itself in `create_ikfast_moveit_plugin.py`, causing errors upon trying to install the package.

**Comment by davetcoleman** [comment]
+1 great point. I probably introduced this discrepancy when making these plugins compatible with multiple planning groups. The format as you said should be:

```
robot_name + "_" + planning_group_name + "_moveit_ikfast_plugin" + "_description.xml"
```

Can you change this commit to a PR?

**Comment by gavanderhoorn** [comment]
You want edf37dc in a separate PR?

**Comment by davetcoleman** [comment]
No, its fine, I just hadn't seen that PR / email yet.
