### ISSUE TITLE
Delete master branch.

### ISSUE THREAD

**Issue by davetcoleman** [moveit/moveit_ikfast#39]
I just made `indigo-devel` the default branch on Github. @gavanderhoorn is `master` ready to be deleted?

**Comment by gavanderhoorn** [comment]
I wanted to wait changing the default branch until after we'd updated rosdistro, wiki and releases.

#37 has been merged, so I guess we can remove `master`.

**Comment by davetcoleman** [comment]
I've just:
- released the `indigo-devel` branch https://github.com/ros/rosdistro/pull/5924
- released the `hydro-devel` branch https://github.com/ros/rosdistro/pull/5925
- deleted the master branch

**Comment by gavanderhoorn** [comment]
Great. Thanks for taking care of that.

PS: I seem to remember tfoote and / or dirk-thomas saying that version numbers of releases in different distributions should never be the same. Something like `1.2.x` in hydro, then `1.3.x` in indigo was recommended. Should we do that here as well?

**Comment by davetcoleman** [comment]
I haven't heard that - I could use a little more motivation for why that is. Notably - the two branches are actually [exactly the same right now](https://github.com/ros-planning/moveit_ikfast/compare/hydro-devel...indigo-devel) so having them the same version number makes sense.

I would like to get the cost feature set to on by default in indigo, however. Then we should diverge the versions.

**Comment by gavanderhoorn** [comment]
@davetcoleman: took some time, but I found it again, see Dirk Thomas in [[ros-release] Ease comparing versions of packages between ROS distros](http://lists.ros.org/pipermail/ros-release/2014-March/004351.html), last bullet.

It's not so much a requirement, more a recommendation I guess.

**Comment by davetcoleman** [comment]
> it is likely that there could be or will be two packages with the same version but different code

But for now there is not a difference in code. Next release we can diverge the version numbers.

**Comment by gavanderhoorn** [comment]
True. I just wanted to draw your attention to it.

**Comment by davetcoleman** [comment]
no problem, thanks!
