### ISSUE TITLE
Release into ROS Jade

### ISSUE THREAD

**Issue by 130s** [moveit/moveit_ikfast#63]
It's required in https://github.com/ros-planning/moveit_ros/issues/692.

If the branches are ready to be released, I can make releases. Right now I see https://github.com/ros-planning/moveit_ikfast/issues/56 that seems better included for the new release?
Let me know.

Thanks!

**Comment by davetcoleman** [comment]
#56 should have been closed

**Comment by 130s** [comment]
Ok, now running pre-release test locally (for Indigo. I noticed that the last release for Indigo was in 2014 and quite a few updates since then).

Note that I'll increment minor version of Jade to 3.2 since it's on separate branch.

**Comment by 130s** [comment]
Done
I https://github.com/ros/rosdistro/pull/12014
J https://github.com/ros/rosdistro/pull/12015

**Comment by davetcoleman** [comment]
Thank you Isaac!
