### ISSUE TITLE
ikfast-kinetic

### ISSUE THREAD

**Issue by MiroslavKohut** [moveit/moveit_ikfast#69]
I recently run into issue with generating ikfast on ros-kinetic. I downloaded and compiled moveit_ikfast kinetic devel. I also generated my ikfast.cpp file and created ikfast plugin. When trying to build ikfast package I am getting following error.

> In file included from /opt/ros/kinetic/include/moveit/macros/class_forward.h:40:0,
>                  from /opt/ros/kinetic/include/moveit/kinematics_base/kinematics_base.h:42,
>                  from /root/catkin_ws/src/abb/abb_irb1600_ikfast_plugin/src/abb_irb1600_mts_manipulator_ikfast_moveit_plugin.cpp:49:
> /opt/ros/kinetic/include/moveit/macros/declare_ptr.h:52:16: error: ‘shared_ptr’ in namespace ‘std’ does not name a template type
>    typedef std::shared_ptr<Type> Name##Ptr;                                                                             \
>                 ^
> /opt/ros/kinetic/include/moveit/macros/class_forward.h:51:3: note: in expansion of macro ‘MOVEIT_DECLARE_PTR’
>    MOVEIT_DECLARE_PTR(C, C);
>    ^
> /opt/ros/kinetic/include/moveit/kinematics_base/kinematics_base.h:137:1: note: in expansion of macro ‘MOVEIT_CLASS_FORWARD’
>  MOVEIT_CLASS_FORWARD(KinematicsBase);
>  ^
> /opt/ros/kinetic/include/moveit/macros/declare_ptr.h:53:16: error: ‘shared_ptr’ in namespace ‘std’ does not name a template type
>    typedef std::shared_ptr<const Type> Name##ConstPtr;
>                 ^
> /opt/ros/kinetic/include/moveit/macros/class_forward.h:51:3: note: in expansion of macro ‘MOVEIT_DECLARE_PTR’
>    MOVEIT_DECLARE_PTR(C, C);
>    ^
> /opt/ros/kinetic/include/moveit/kinematics_base/kinematics_base.h:137:1: note: in expansion of macro ‘MOVEIT_CLASS_FORWARD’
>  MOVEIT_CLASS_FORWARD(KinematicsBase);
>  ^
> abb/abb_irb1600_ikfast_plugin/CMakeFiles/abb_irb1600_mts_manipulator_moveit_ikfast_plugin.dir/build.make:62: recipe for target 'abb/abb_irb1600_ikfast_plugin/CMakeFiles/abb_irb1600_mts_manipulator_moveit_ikfast_plugin.dir/src/abb_irb1600_mts_manipulator_ikfast_moveit_plugin.cpp.o' failed
> make[2]: *** [abb/abb_irb1600_ikfast_plugin/CMakeFiles/abb_irb1600_mts_manipulator_moveit_ikfast_plugin.dir/src/abb_irb1600_mts_manipulator_ikfast_moveit_plugin.cpp.o] Error 1
> CMakeFiles/Makefile2:13767: recipe for target 'abb/abb_irb1600_ikfast_plugin/CMakeFiles/abb_irb1600_mts_manipulator_moveit_ikfast_plugin.dir/all' failed
> make[1]: *** [abb/abb_irb1600_ikfast_plugin/CMakeFiles/abb_irb1600_mts_manipulator_moveit_ikfast_plugin.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> [100%] Built target binpicking_demo
> Makefile:138: recipe for target 'all' failed
> make: *** [all] Error 2
> Invoking "make -j8 -l8" failed

Thank you for your help

**Comment by gavanderhoorn** [comment]
This repository has been integrated into [ros-planning/moveit](https://github.com/ros-planning/moveit) quite some time ago already.

If you still run into the same problem when working with the `moveit_kinematics` package from that repository, could I ask you to open a new issue over at the `moveit` issue tracker?
